### ISSUE TITLE
Deprecate EtherToken

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#245]
I was reviewing BCC's chief evangelist (@decanus) code for Dexy and I was really surprised at how clean a Vault that handles ETH and tokens can be made, making the UX actually better than wrapping and unwrapping tokens. From an architectural design point of view it is kind of elegant to just handle tokens, but given how clean this looks I'm really having second thoughts.

Pasting some of Dean's code here:
```solidity
address constant public ETH = 0x0;

// ETH and erc20
function deposit(address token, uint amount) external payable {
        require(token == ETH || msg.value == 0);

        uint value = amount;
        if (token == ETH) {
            value = msg.value;
        }

        if (token != ETH) {
            require(ERC20(token).transferFrom(msg.sender, address(this), value));
        }

        depositFor(msg.sender, token, value); // pretty much just accounting
}

// erc777
function tokenFallback(address from, uint value, bytes data) public {
        depositFor(from, msg.sender, value);
}

function withdraw(address token, uint amount) external {
        require(balanceOf(token, msg.sender) >= amount);

        balances[token][msg.sender] = balances[token][msg.sender].sub(amount);
        accounted[token] = accounted[token].sub(amount);

        if (token == ETH) {
            msg.sender.transfer(amount);
        } else if (isERC777[token]) {
            ERC777(token).send(msg.sender, amount);
        } else {
            ERC20(token).transfer(msg.sender, amount);
        }

        Withdrawn(msg.sender, token, amount);
}

```

The Vault is not something we should be updating frequently, so I would like to push this for the new audit and have WHG review it too.

@aragon/aragon-core please give your opinion ASAP.

**Comment by onbjerg** [comment]
For the vault, you would also have to manage allowances for ETH then, right?

Right now we also discourage the use of `transferTokens` in favor of allowances, but that would not be the case anymore, since ETH could only be transferred using that function then - so apps might actually need multiple permissions now, just to transfer ETH (e.g. an app right now might only need to request for allowances to transfer tokens, including WETH, but because of how this system would work, they would also need the transfer role to transfer ETH).

Honestly, it feels a bit (for our use case) like shifting an edge case from the user to the contract, which might be nice for some things, but not sure if adding complexity to the Vault is a good idea.

**Comment by izqui** [comment]
> For the vault, you would also have to manage allowances for ETH then, right?

That concept doesn't exist in ETH.

> Right now we also discourage the use of transferTokens in favor of allowances

That's no longer the case. We use transfers everywhere.

> apps might actually need multiple permissions now, just to transfer ETH.

We can keep everything in the transfer function and therefore just have role for transfers, that can already be parametrized depending on token address.

**Comment by onbjerg** [comment]
>That concept doesn't exist in ETH.

And it shouldn't?

**Comment by izqui** [comment]
`ERC20.approve` should be killed with fire IMO :)

**Comment by onbjerg** [comment]
👌

**Comment by bingen** [comment]
I guess we could use an `else` here, and I see the benefit of avoiding ether token dependency, but I don't see how this is cleaner than just one line:
```
        if (token == ETH) {
            value = msg.value;
        }

        if (token != ETH) {
            require(ERC20(token).transferFrom(msg.sender, address(this), value));
        }
```
Besides I guess calling this function `deposit` is kind of messy, as sometimes you have to use `value` (for ETH) and sometimes `amount` (for tokens).
Anyway, I'm not opposed to it.

**Comment by sohkai** [comment]
> People are so confused about WETH and it doesn't look like ETH is going to turn into a token any time soon.

This is the best argument for doing this. If the dream of WETH / tokenized ETH seems to be vanishing, we should make these architectural changes to make our system be as flexible as possible for others.

Assuming we'll also be changing the contracts to support ERC-777, we'll have more than one token implementation to handle anyway so adding native ETH is an (arguably easier) 2->3 jump rather than 1->2.

-----------

But that being said, I wonder if having a separate native ETH vault would be a better fit to our "do one thing and do it well" strategy for apps (and then generalizing this idea so all token could have their own vaults, e.g. 223, 667, 827, etc)? Or would that get confusing quick?

What if we decoupled the deposit functionality from the withdraw / approve / etc functionality such that a "payment router" app was installed on each DAO that understood where to proxy payments to? That way you would specify one "router" to send any funds to, so it's less confusing, but if an app needed a certain functionality / token type (e.g. approve on an ERC20), you would ask for permissions in the corresponding vault?

--------

One thing I wouldn't mind doing in the combined vault is adding "sugar" functions that simplify the native ETH path, e.g:

```
function deposit() external payable;

function withdraw(uint amount) external;
```

**Comment by bingen** [comment]
I completely agree with this:

>>    People are so confused about WETH and it doesn't look like ETH is going to turn into a token any time soon.

> This is the best argument for doing this. If the dream of WETH / tokenized ETH seems to be vanishing, we should make these architectural changes to make our system be as flexible as possible for others.

> Assuming we'll also be changing the contracts to support ERC-777, we'll have more than one token implementation to handle anyway so adding native ETH is an (arguably easier) 2->3 jump rather than 1->2.

**Comment by decanus** [comment]
If I can chime in here. I definitely don’t think you are doing anyone a favor with WETH. Even if it were to be implemented, (which I don’t see happening) you are punishing users with extra transactions and terrible UX. So if the code may now be 3 lines instead of 1 i think it is a solid trade-off for users sake.

**Comment by bingen** [comment]
Fair enough. Although I would separate `deposit` function into two different ones, one (payable) for ETH and one for ERC20 tokens. There's already one separated for ERC777 tokens, the code would look cleaner in my opinion (no `require`, no `if`s) and the UX would be better IMO too, as I said  before, calling the function with different parameters for ETH and tokens makes it kind of confusing.
In our case, we access the vault through finance app, so we could move the problem there (following the idea in the second comment by @sohkai , to keep the Vault simple). It's actually partially [happening](https://github.com/aragon/aragon-apps/blob/master/apps/finance/contracts/Finance.sol#L497).

**Comment by bingen** [comment]
About splitting, something like this:
```
// ETH
function deposit() external payable {
    depositFor(msg.sender, ETH, msg.value); // pretty much just accounting
}

// erc20
function depositToken(address token, uint amount) external {
    require(ERC20(token).transferFrom(msg.sender, address(this), amount));

    depositFor(msg.sender, token, value); // pretty much just accounting
}
```

**Comment by izqui** [comment]
We could explore https://github.com/decanus/dynamic-vault too, but this is now aragon-apps territory. 

Let's continue convo here https://github.com/aragon/aragon-apps/issues/125
