### ISSUE TITLE
Revert with reason

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#438]
On mainnet having revert reasons will help us debug issues when transactions revert.

There is no clear standard for how this should be done, other projects seem to just be returning error strings. Adding long strings bloats the contract bytecode and the cost for deployment.

I think we should at least add revert reasons for everything that may cause a revert in `AppProxy` and `KernelProxy`, as that code will remain static. At the same time, the proxies should be as small as possible so they are cheap to deploy, so we should be careful with what errors we return.

`DelegateProxy` forwards the error data if a revert occurs in the `delegatecall`, so if an app reverts with reason the error message would propagate up the call stack. We should still test that this is indeed behaving as we expect (**Edit:** tested, it works).

**Comment by sohkai** [comment]
@izqui I was thinking that, as a potential way to avoid spoofing of the error messages, the `DelegateProxy` could detect if an error happened and return a differently formatted `returndata`.

Instead of just:

```solidity
let ptr := mload(0x40)
returndatacopy(ptr, 0, size)
switch result case 0 { revert(ptr, size) }
```

We could encode something like `1<error data>` (where `1` is the "app" error namespace and `0` could be the proxy's own error namespace).

---------------

However, this might be too much, given we can always look at the debug trace and also spot if it was the app's base contract failing by the gas cost.

**Comment by izqui** [comment]
For simplicity I would avoid manipulating the returned error strings as the returned data is ABI encoded, and for adding a new char we would need to decode and re-encode the data.

The spoofing we are trying to protect against is apps returning errors that are the same as the proxy errors, right? Since the proxy can only revert before performing the the delegatecall, the spoofing would be pretty easy to detect, as native proxy errors are only 'legit' if the proxy doesn't perform a `delegatecall` (which can be easily seen by analyzing a debug trace).

**Comment by izqui** [comment]
After implementing them, I changed my mind and I think we should have revert reasons everywhere but on proxies (See https://github.com/aragon/aragonOS/pull/440#issuecomment-430323016)
